@startuml

title __DTO's Class Diagram__\n

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.dto {
        class BookAndRating {
            - isbn : String
            - title : String
            - author : String
            - yearOfPublication : Integer
            - publisher : String
            - imageUrlS : String
            - imageUrlM : String
            - imageUrlL : String
            - rating : Float
            - description : String
            + BookAndRating()
            + BookAndRating()
            ~ getIsbn()
            ~ getBook_Title()
            ~ getBook_Author()
            ~ getYear_Of_Publication()
            ~ getPublisher()
            ~ getImage_Url_S()
            ~ getImage_Url_M()
            ~ getImage_Url_L()
            ~ getAverage()
            ~ getDescription()
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.dto {
        interface IBookAndRating {
            {abstract} + getIsbn()
            {abstract} + getBook_Title()
            {abstract} + getBook_Author()
            {abstract} + getYear_Of_Publication()
            {abstract} + getPublisher()
            {abstract} + getImage_Url_S()
            {abstract} + getImage_Url_M()
            {abstract} + getImage_Url_L()
            {abstract} + getAverage()
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.dto {
        interface IBookReview {
            {abstract} + getReview_Id()
            {abstract} + getUsername()
            {abstract} + getText()
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.dto {
        interface IUserHistoryItem {
            {abstract} + getIsbn()
            {abstract} + getBook_Title()
            {abstract} + getBook_Author()
            {abstract} + getBook_Rating()
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.dto {
        class StringTO {
            - stringParameter : String
            + StringTO()
            + StringTO()
            + getStringParameter()
            + setStringParameter()
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.dto {
        class UserRegistrationDto {
            - username : String
            - password : String
            - confirmPassword : String
            - email : String
            - confirmEmail : String
            - terms : Boolean
            + getUsername()
            + setUsername()
            + getPassword()
            + setPassword()
            + getConfirmPassword()
            + setConfirmPassword()
            + getEmail()
            + setEmail()
            + getConfirmEmail()
            + setConfirmEmail()
            + getTerms()
            + setTerms()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
