@startuml

title __MAXIMALIBRIV2's Class Diagram__\n

  package  {
    package com.maximaLibri.maximaLibriV2 {
      class AddAdmin {
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.dataGeneration {
        class AddDescriptionAndKeywordsForBooks {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.controller {
        class AddRoleToModel {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.controller {
        class AdminController {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.model {
        class Book {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.dto {
        class BookAndRating {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.controller {
        class BookController {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.model {
        class BookRating {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.model {
        class BookRatingId {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.repository {
        interface BookRatingRepository {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.repository {
        interface BookRepository {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.service {
        class BookService {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.model {
        class BxUser {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.repository {
        interface BxUserRepository {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.model {
        class ConfirmationToken {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.repository {
        interface ConfirmationTokenRepository {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.service {
        class EmailSenderService {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.constraint {
        class EmailValidator {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.controller {
        class ErrorController {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.constraint {
        interface FieldMatch {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.constraint {
        class FieldMatchValidator {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.dto {
        interface IBookAndRating {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.dto {
        interface IBookReview {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.dto {
        interface IUserHistoryItem {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.controller {
        class MainController {
        }
      }
    }
  }
  

  package  {
    class MavenWrapperDownloader {
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      class MaximaLibriV2Application {
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.recommender {
        class RecommenderService {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.controller {
        class RegistrationController {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.model {
        class Review {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.repository {
        interface ReviewRepository {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.model {
        class Role {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.model {
        enum RoleName {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.repository {
        interface RoleRepository {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.config {
        class SecurityConfiguration {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.dto {
        class StringTO {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.model {
        class User {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.controller {
        class UserController {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.dto {
        class UserRegistrationDto {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.repository {
        interface UserRepository {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.service {
        class UserService {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.constraint {
        interface ValidEmail {
        }
      }
    }
  }
  

  AddAdmin o-- UserService : userService
  AddAdmin o-- RoleRepository : roleRepository
  AddAdmin o-- UserRepository : userRepository
  AddDescriptionAndKeywordsForBooks o-- BookRepository : bookRepository
  AdminController o-- UserService : userService
  AdminController o-- BookService : bookService
  BookController o-- BookService : bookService
  BookController o-- UserService : userService
  BookRating o-- BookRatingId : bookRatingId
  BookRatingId -up-|> Serializable
  BookService o-- BookRepository : bookRepository
  BookService o-- BookRatingRepository : bookRatingRepository
  BookService o-- ReviewRepository : reviewRepository
  ConfirmationToken o-- User : user
  EmailValidator -up-|> ConstraintValidator
  FieldMatchValidator -up-|> ConstraintValidator
  MainController o-- BookService : bookService
  MainController o-- UserService : userService
  MainController o-- EmailSenderService : emailSenderService
  RecommenderService o-- UserService : userService
  RecommenderService o-- BookRatingRepository : bookRatingRepository
  RecommenderService o-- BookRepository : bookRepository
  RegistrationController o-- UserService : userService
  RegistrationController o-- UserRepository : userRepository
  RegistrationController o-- ConfirmationTokenRepository : confirmationTokenRepository
  RegistrationController o-- EmailSenderService : emailSenderService
  Role o-- RoleName : name
  SecurityConfiguration -up-|> WebSecurityConfigurerAdapter
  SecurityConfiguration o-- UserService : userService
  UserController o-- UserService : userService
  UserController o-- BookRatingRepository : bookRatingRepository
  UserController o-- RecommenderService : recommenderService
  UserService -up-|> UserDetailsService
  UserService o-- UserRepository : userRepository
  UserService o-- RoleRepository : roleRepository
  UserService o-- BookRatingRepository : bookRatingRepository
  UserService o-- ReviewRepository : reviewRepository


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
