@startuml

title __REPOSITORY's Class Diagram__\n

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.repository {
        interface BookRatingRepository {
            {abstract} + findRatingsByUserId()
            {abstract} + getBookRating()
            {abstract} + getAvg()
            {abstract} + getTop10()
            {abstract} + getUserHistory()
            {abstract} + findBookAndRatingById()
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.repository {
        interface BookRepository {
            {abstract} + findSearchResults()
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.repository {
        interface BxUserRepository {
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.repository {
        interface ConfirmationTokenRepository {
            {abstract} + findByConfirmationToken()
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.repository {
        interface ReviewRepository {
            {abstract} + findByUserIdAndIsbn()
            {abstract} + findReviewsForBook()
            {abstract} + findReviewsByUser()
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.repository {
        interface RoleRepository {
            {abstract} + findByName()
        }
      }
    }
  }
  

  package  {
    package com.maximaLibri.maximaLibriV2 {
      package com.maximaLibri.maximaLibriV2.repository {
        interface UserRepository {
            {abstract} + findByEmail()
            {abstract} + findByUsername()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
